services:
  go_random_logger:
    build:
      context: .
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
    image: $REGISTRY/$GITHUB_USERNAME/go_random_logger:$TAG_VERSION
    volumes:
      - /var/log:/var/log