name: Publish Docker Image

on:
  push:
    branches:
      - test-ci

env:
  REGISTRY: ghcr.io
  TAG_VERSION: 1.1
  GITHUB_USERNAME: veben

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # Required to push tags and create new releases
      packages: write    # Required to push Docker images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load .env file
        run: |
          if [ -f .env ]; then
            source .env
            echo "Loaded environment variables from .env"
          else
            echo ".env file not found"
          fi

      - name: Create and push Git tag
        run: |
          git tag ${{ env.TAG_VERSION }}
          git push origin ${{ env.TAG_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and push Docker image via docker-compose
        run: |
          docker-compose build
          docker-compose push